runtime: nodejs8
instance_class: F1
automatic_scaling:
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 1500ms
  max_pending_latency: 1500ms
  max_concurrent_requests: 80
handlers:
- url: /assets
  static_dir: server/public/assets
- url: /loaderio-e361c7eaca7bf514d3b83b1064fd9380.txt
  static_files: server/public/loaderio-e361c7eaca7bf514d3b83b1064fd9380\.txt
  upload: server/public/loaderio-e361c7eaca7bf514d3b83b1064fd9380\.txt
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
