name: Build

on:
  pull_request:
    paths:
      - 'client/**'
      - 'server/src/**'
      - 'shared/src/**'
      - '.github/workflows/build.yml'
      - 'package.json'
      - 'tsconfig.json'
      - 'webpack.config.js'
      - 'yarn.lock'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install yarn
        run: npm install -g yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run yarn install
        run: yarn install
      - name: Create server-config.ts
        run: mv server-config.template.ts server-config.ts
        working-directory: server/src
      - name: Run yarn build
        run: yarn run build
